version: '3'
services:
  app_test:
    container_name: uptime-monitoring-service_test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - api_test:/app/src/app/

volumes:
  api_test:
