// Code generated by MockGen. DO NOT EDIT.
// Source: UptimeMonitoringService/database (interfaces: RepositoryController)

// Package mocks is a generated GoMock package.
package mocks

import (
	database "UptimeMonitoringService/database"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepositoryController is a mock of RepositoryController interface
type MockRepositoryController struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryControllerMockRecorder
}

// MockRepositoryControllerMockRecorder is the mock recorder for MockRepositoryController
type MockRepositoryControllerMockRecorder struct {
	mock *MockRepositoryController
}

// NewMockRepositoryController creates a new mock instance
func NewMockRepositoryController(ctrl *gomock.Controller) *MockRepositoryController {
	mock := &MockRepositoryController{ctrl: ctrl}
	mock.recorder = &MockRepositoryControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepositoryController) EXPECT() *MockRepositoryControllerMockRecorder {
	return m.recorder
}

// DatabaseCreate mocks base method
func (m *MockRepositoryController) DatabaseCreate(arg0 *database.URLData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseCreate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DatabaseCreate indicates an expected call of DatabaseCreate
func (mr *MockRepositoryControllerMockRecorder) DatabaseCreate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseCreate", reflect.TypeOf((*MockRepositoryController)(nil).DatabaseCreate), arg0)
}

// DatabaseDelete mocks base method
func (m *MockRepositoryController) DatabaseDelete(arg0 *database.URLData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseDelete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DatabaseDelete indicates an expected call of DatabaseDelete
func (mr *MockRepositoryControllerMockRecorder) DatabaseDelete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseDelete", reflect.TypeOf((*MockRepositoryController)(nil).DatabaseDelete), arg0)
}

// DatabaseGet mocks base method
func (m *MockRepositoryController) DatabaseGet(arg0 *database.URLData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseGet", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DatabaseGet indicates an expected call of DatabaseGet
func (mr *MockRepositoryControllerMockRecorder) DatabaseGet(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseGet", reflect.TypeOf((*MockRepositoryController)(nil).DatabaseGet), arg0)
}

// DatabaseSave mocks base method
func (m *MockRepositoryController) DatabaseSave(arg0 *database.URLData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseSave", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DatabaseSave indicates an expected call of DatabaseSave
func (mr *MockRepositoryControllerMockRecorder) DatabaseSave(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseSave", reflect.TypeOf((*MockRepositoryController)(nil).DatabaseSave), arg0)
}
